server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_spring_boot_application?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: gjb200069
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1  # Redis服务器IP
    port: 6379             # Redis端口
#    password: admin
    database: 0            # 使用默认数据库
    timeout: 5000          # 连接超时时间（毫秒）
    lettuce:               # 使用Lettuce连接池（Spring Boot 2.x默认）
      pool:
        max-active: 8      # 最大连接数
        max-wait: -1       # 连接池最大阻塞等待时间（-1表示无限制）
        max-idle: 8        # 最大空闲连接
        min-idle: 0        # 最小空闲连接
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      retry:
        max-attempts: 3       # 最大重试次数
        initial-interval: 1000 # 初始重试间隔（毫秒）
        multiplier: 2.0       # 间隔倍数（指数退避）
      ack-mode: MANUAL_IMMEDIATE
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #auto-offset-reset: earliest      # 从最早的消息开始消费（可选：latest）
      enable-auto-commit: false

logging:
  level:
    org.springframework.core.env: TRACE
    #    org:
    #      mybatis: DEBUG

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:org.example.dao/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true